require 'rake/testtask'
require 'rubocop/rake_task'

RuboCop::RakeTask.new

Rake::TestTask.new do |t|
  t.test_files = FileList['*_test.rb']
  t.verbose = true
end

task default: %i(test rubocop)

task :console do
  sh 'irb -rubygems -I lib -I extra -r ./solution.rb'
end
