require 'rake/testtask'
require 'rubocop/rake_task'

RuboCop::RakeTask.new

Rake::TestTask.new do |t|
  t.test_files = FileList['*_test.rb']
  t.verbose = true
end

task default: %i(test rubocop)

task :console do
  require 'irb'
  require 'irb/completion'
  require 'rubygems'
  require 'bundler/setup'
  require_relative 'solution'
  ARGV.clear
  IRB.start
end

task :console_1 do
  sh "irb -rubygems -I lib -I  extra -r ./solution.rb"
end
